# This config is different from config.toml in this directory, as the latter is recognized by Cargo.
# This file is placed in ./../.cargo/config.toml on CI runs. Cargo then merges Zeds .cargo/config.toml with ./../.cargo/config.toml
# with preference for settings from Zeds config.toml.
# TL;DR: If a value is set in both ci-config.toml and config.toml, config.toml value takes precedence.
# Arrays are merged together though. See: https://doc.rust-lang.org/cargo/reference/config.html#hierarchical-structure
# CI denies warnings in workspace packages without overriding their target-specific
# compiler flags or turning dependency warnings into errors.
[build]
warnings = "deny"

# We don't need fullest debug information for dev stuff (tests etc.) in CI.
[profile.dev]
debug = "limited"


